from typing import TypedDict, Annotated, Sequence
import operator

def append_reducer(left: list, right: list) -> list:
    """
    A custom reducer to cleanly append new fetched data pieces
    instead of overwriting the previous state.
    """
    return left + right

class AgentState(TypedDict):
    """
    Global state schema acting as a thread-safe context ledger for the AlphaAgent topology.
    """
    # Target stock/company identifier
    ticker: str

    # Original question or specific focus area from the user
    user_query: str

    # Raw intelligence gathered from DB or scraping.
    # Annotated with a custom reducer to append data pieces sequentially.
    raw_data: Annotated[list[dict],append_reducer]

    # The drafted financial analysis report generated by the Analyst Node
    financial_report: str

    # Feedback and audit notes from the Critic Node
    critique: str

    # Circuit breaker counter to prevent infinite token-burning loops
    critique_count: int