from typing import TypedDict, Annotated, Sequence
import operator

def append_reducer(left: list, right: list) -> list:
    """
    An incremental Reducer with physical deduplication capabilities, 
    preventing identical data from endlessly accumulating across multiple 
    error-correction cycles and overwhelming the context window.
    """
    if not left:
        return right
    if not right:
        return left
        
    # Perform deduplication and stitching based on the content or hash of the `content`.
    seen_contents = {chunk['content'] for chunk in left}
    new_chunks = [chunk for chunk in right if chunk['content'] not in seen_contents]
    
    return left + new_chunks

class AgentState(TypedDict):
    """
    Global state schema acting as a thread-safe context ledger for the AlphaAgent topology.
    """
    # Target stock/company identifier
    ticker: str

    # Original question or specific focus area from the user
    user_query: str

    # Raw intelligence gathered from DB or scraping.
    # Annotated with a custom reducer to append data pieces sequentially.
    raw_data: Annotated[list[dict],append_reducer]

    # The drafted financial analysis report generated by the Analyst Node
    financial_report: str

    # Feedback and audit notes from the Critic Node
    critique: str

    # Circuit breaker counter to prevent infinite token-burning loops
    critique_count: int

    # Next action depending on Supervisor Node
    next_action: str