from typing import TypedDict, Annotated, List, Dict, Any
import operator


def append_reducer(left: list, right: list) -> list:
    """
    Incrementally append new data while preventing duplicate content
    from accumulating across correction cycles.
    """
    if not left:
        return right

    if not right:
        return left

    seen_contents = {chunk["content"] for chunk in left}
    new_chunks = [
        chunk
        for chunk in right
        if chunk["content"] not in seen_contents
    ]

    return left + new_chunks


class AgentState(TypedDict):
    """
    Global state schema acting as a shared context ledger
    for the AlphaAgent workflow.
    """

    # Target stock/company identifier
    ticker: str

    # Original question or focus area from the user
    user_query: str

    # Raw intelligence gathered from the database or external sources
    raw_data: Annotated[list[dict], append_reducer]

    # Availability status for each financial data category
    data_quality: Dict[str, str]

    # Machine-readable list of missing data categories
    missing_data: List[str]

    # Human-readable limitations that should be disclosed in the report
    data_limitations: List[str]

    # Financial analysis report generated by the Analyst Node
    financial_report: str

    # Feedback and audit notes generated by the Critic Node
    critique: str

    # Circuit-breaker counter preventing infinite correction loops
    critique_count: int

    # Next action selected by the Supervisor Node
    next_action: str

    # Events displayed by the frontend
    events: List[Dict[str, Any]]